### ISSUE TITLE
Base Uri

### ISSUE THREAD

**Issue by neilgierman** [latera/homs#148]
I am trying to load HOMS as a back-end using Apache's ProxyPass[Reverse]. However all of the links and assets in HOMS seem to be absolute URLs ("/users/sign_in" for example) so when I forward a Location on my front-end to the back-end it doesn't work.

An example is in my Apache front-end, I have:

ProxyPass "/homs" "http://localhost:3000"
ProxyPassReverse "/homs" "http://localhost:3000"

When I go to "http://my.front.end/homs" it tries to redirect to "http://my.front.end/users/sign_in" instead of "http://my.front.end/homs/users/sign_in".

I didn't see anywhere in the base config yaml file about how to specify a Base Uri so that all of the links will have a path inserted before the homs assets. An alternative would be to use relative URIs instead of absolute.

**Comment by sugarfree1** [comment]
Hello, @neilgierman 
We don't have such option right now. 
It looks like you want to set URL prefix in config for all URLs in HOMS. Did I get your idea correctly?
And if possible, could you explain why you need it?

**Comment by neilgierman** [comment]
Yes, You understand my request correctly. The reason I am requesting this is because I don't want to stand up a different server, nor do I want to expose another port. I already have an existing front end (website) that I want to publish the HOMS service as a subfolder under my existing environment.
