### ISSUE TITLE
Could not create admin user for Camunda

### ISSUE THREAD

**Issue by loumarven** [latera/homs#434]
Hi,

I'm at step 10 in homs README (Navigate to Camunda Admin and create admin user with credentials equal to BPM_USER:BPM_PASSWORD values from .env file.).
I get redirected to http://localhost:8766/camunda/app/welcome/default/#/login, so I couldn't create an admin user for Camunda.

How do I create an admin user for Camunda?
Am I missing a step?

Thank you!

**Comment by dolfinus** [comment]
Hello.

If you use the latest Camunda image you can skip this step because user will be [created automatically](https://github.com/latera/camunda-ext/blob/master/seed/src/main/groovy/org/camunda/latera/bpm/configuration/SeedApplication.groovy#L45) using credentials you've provided in environment variables.
Please sign in using BPM_USER:BPM_PASSWORD as username and password.

**Comment by loumarven** [comment]
Hi @dolfinus. Thank you for responding to my issue.
I tried to sign in using `kermit` as username and `kermit` as the password (default BPM_USER:BPM_PASSWORD), but login fails (Wrong credentials or missing access rights to application).
What do you suggest I try next?

_Note_:
I am running this on a mac, with postgresql installed view brew (`brew install postgresql`).
Do I change the `HOMS_DB_PATH` and `BPM_DB_PATH`?

Thank you.

**Comment by dolfinus** [comment]
Can you please provide your docker-compose.yml and .env files?

**Comment by dolfinus** [comment]
I've just checked startup scripts and .env file examples again and found that in case then you set ADMIN_PASSWORD environment variable it is being used by both Camunda and Hydra OMS as password source. So you should try credentials `kermit:changeme`.

**Comment by loumarven** [comment]
I was able to get past step 10 with this combination:  
username: `kermit`
password: `changeme`

I guess we can update the steps in the README so others wouldn't run with the same issue?  

Thanks a lot @dolfinus!

**Comment by loumarven** [comment]
A quick `grep` of "BPM_PASSWORD" shows that its value is not used(?).

[If `ADMIN_PASSWORD` is not set in `.env`, the admin password defaults to `changeme`](https://github.com/latera/homs/blob/ad9431a677e931c40ad6717cbaa944b0d2d643a3/db/seeds.rb#L15)

**Comment by dolfinus** [comment]
You are searching in wrong repo. Camunda is located here: https://github.com/latera/camunda-ext

**Comment by dolfinus** [comment]
We'll update installation manual here: https://github.com/latera/homs/pull/443
