### ISSUE TITLE
Homs login not working

### ISSUE THREAD

**Issue by riteshvsharma** [latera/homs#454]
Good day,

I am trying to setup hydra-oms in development mode. I have completed the setup, I am able to login to camunda console and the Homs page is coming up on the port 3000.

However I am not able to login in to Homs using the default username and password. When I check the database I don't see any records in users table.

Kindly advise how to create the default user.

Thanks

**Comment by sugarfree1** [comment]
Hello,

Try ```rake db:migrate``` and then ```rake db:seed```, please. Hope it helps.

**Comment by sugarfree1** [comment]
And don't forget to set env variable before migrating and seeding: ```export SEED_DB=true```

**Comment by riteshvsharma** [comment]
Good day Dmitry,

Thank you. IT WORKED.

Best, Ritz
+27 71 383 2274 | +91 9833 70 7489
