### ISSUE TITLE
homs has downloaded over 2GB of data uppon installation, WHY!!

### ISSUE THREAD

**Issue by Mr1Bil** [latera/homs#520]
why do i need to download and install over 2GB of data for only 50MB website

**Comment by flash-gordon** [comment]
@Mr1Bil what makes you think it's a "50 MB website"? HOMS require quite a bunch of parts to be working. They are listed in the [compose file](https://github.com/latera/homs/blob/master/docker-compose.yml). Clearly, it cannot be lightweight. The part stored in this repository is actually quite small but dependency are unavoidably larger. I don't think we can do anything about it.
