### ISSUE TITLE
Add fresher doc about ruby-oci8

### ISSUE THREAD

**Issue by Vin0uz** [latera/homs#541]
Hi guys, and thanks for the amazing tool !  

I've been trying to install today, without Oracle and it turned out to raise an issue with ruby-oci8.

Fortunately, I was not the first one to meet issues with it (see [this SO topic](https://stackoverflow.com/questions/11894194/how-to-install-ruby-oci8/) but still, it was very troubling to find the solution. The one from SO didn't work, considering it's 5 years old, it makes sense, so I kept digging.

So far, I found this [documentation from ruby-oci8 docs](https://www.rubydoc.info/github/kubo/ruby-oci8/file/docs/install-on-osx.md), which led me straight to it, so I thought it might be useful to add it somewhere in the doc 🤷‍♂️ 

(It's permitting to use latest version of the client (19.8), didn't test it very long, so I cannot assure that this is completely compatible)

**Comment by TimAle** [comment]
Hi Vinhas, thanks!

If you want to install HOMS without Oracle support for development purposes you should run 
```
bundle config set without 'oracle'
bundle install
```
, so `ruby-oci8` won't be installed.

I'll update the readme in https://github.com/latera/homs/pull/544

**Comment by Vin0uz** [comment]
I installed Oracle since 😅  but thanks 🙌
