### ISSUE TITLE
Little improvments to the doc

### ISSUE THREAD

**Issue by Vin0uz** [latera/homs#542]
It's me again 😅 

I went through the installation documentation and noticed this little things : 
-> Nothing said about bundle / yarn install ; Although this project seems to be used by advanced users, I think it could be nice to remind them when to do it to avoid issues. 

-> Since Rails 5 (I think), rails supports rake commands and the norm seems nowadays to be `rails db:migrate` and `rails db:seed` instead of `rake` ; This is mainly a convention matter, not really a problem.

**Comment by TimAle** [comment]
Good notice, thank you!
https://github.com/latera/homs/pull/544
