### ISSUE TITLE
docker compose - latera/homs container crashes.

### ISSUE THREAD

**Issue by mohamed-eldafrawi** [latera/homs#57]
When i try to install Hydra OMS using Docker Compose, latera/homs contianer crashes immediately.

This is a Copy of the container logs:

cp: target '/opt/homs/config/' is not a directory
cp: cannot stat 'config/activiti.yml.sample': No such file or directory
sed: can't read config/activiti.yml: No such file or directory
sed: can't read config/activiti.yml: No such file or directory
sed: can't read config/activiti.yml: No such file or directory
cp: cannot stat 'config/database.yml.sample': No such file or directory
sed: can't read config/database.yml: No such file or directory
^C/usr/local/lib/ruby/2.2.0/rake.rb:36:in `require': Interrupt
	from /usr/local/lib/ruby/2.2.0/rake.rb:36:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rake-10.4.2/bin/rake:31:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rake-10.4.2/bin/rake:31:in `<top (required)>'
	from /usr/local/bundle/bin/rake:16:in `load'
	from /usr/local/bundle/bin/rake:16:in `<main>'
rake aborted!
LoadError: cannot load such file -- /opt/homs/config/application
/opt/homs/Rakefile:4:in `require'
/opt/homs/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)
/usr/local/bundle/gems/thin-1.6.4/lib/thin/runner.rb:147:in `parse!': missing argument: -e (OptionParser::MissingArgument)
	from /usr/local/bundle/gems/thin-1.6.4/lib/thin/runner.rb:50:in `initialize'
	from /usr/local/bundle/gems/thin-1.6.4/bin/thin:6:in `new'
	from /usr/local/bundle/gems/thin-1.6.4/bin/thin:6:in `<top (required)>'
	from /usr/local/bundle/bin/thin:16:in `load'
	from /usr/local/bundle/bin/thin:16:in `<main>'

**Comment by unix-way** [comment]
Hello,

We have fixed the container and built a new version. You should now type
```docker-compose pull homs```
in the directory where you have downloaded the docker-compose.yml file and then run the container by issuing
```docker-compose up -d```.

Sorry for the inconvenience it might cause you.

**Comment by mohamed-eldafrawi** [comment]
Thanks.
