### ISSUE TITLE
Docker image?

### ISSUE THREAD

**Issue by buger** [latera/homs#8]
Hello! Looks cool, hello @nixikanius  :)

I would like to try it, really, but installation seems to be so complex and has a lot of dependencies.

Adding Docker image should help a lot.

**Comment by nixikanius** [comment]
Hello @buger!

We are already working on docker container and will provide it ASAP.

**Comment by nixikanius** [comment]
@bugger we added [docker image](https://github.com/latera/homs#using-docker)!
